- name: Add upgraded bash to trusted shells
  lineinfile: 
    path: /etc/shells
    line: "{{ lookup('env', 'HOMEBREW_PREFIX') }}/bin/bash"
  become: true

- name: Set correct bash shell for user
  user: 
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ lookup('env', 'HOMEBREW_PREFIX') }}/bin/bash"
  become: true
