- name: Add upgraded bash to trusted shells
  lineinfile: 
    path: /etc/shells
    regexp: '^\/usr\/local\/bin\/bash'
    line: /usr/local/bin/bash
  become: true

- name: Set correct bash shell for user
  user: 
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/local/bin/bash
  become: true
