- name: Check for VSCode config
  stat:
    path: "{{ code.config_path }}"
  register: code_config
  tags: 
    - code

- name: Configure Tower
  block: 

    - name: Configure code
      ansible.builtin.shell: | 
        code ~/Projects/jamesdh/dotfiles 
        cliclick w:3000 c:575,555 w:200 c:900,600 w:200 c:655,160 w:200 c:600,190 w:200 c:810,830
        osascript -e 'tell application "Code" to quit'

  when: not code_config.stat.exists
  tags: 
    - code
