---

- name: Checking for Contexts license file
  stat:
    path: "{{ contexts.license_path }}"
  register: license_file
  tags: 
    - contexts
    - settings

- name: Configure Contexts
  block: 
    
    - name: Create Contexts application folder
      file: 
        path: "{{ contexts.license_path | dirname }}"
        state: directory

    - name: Create Contexts license file
      file: 
        path: "{{ contexts.license_path }}"
        state: touch

    - name: Download license
      get_url:
        url: '{{ contexts.license_url }}'
        dest: "{{ contexts.license_path }}"
        mode: 0644

    - name: Open license file to register license with Contexts
      shell: "open '{{ contexts.license_path }}'"

  when: not license_file.stat.exists
  tags: 
    - contexts
    - settings