- name: Create iTerm dirs
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop: 
    - "{{ iterm.dynamic_profile_dir }}"
    - "{{ iterm.autorun_dir }}"
  tags: 
    - iterm

- name: Link iTerm Dynamic Profile 
  file: 
    src: "{{role_path}}/files/iTerm/iTerm.json"
    path: "{{iterm.dynamic_profile_dir}}/iTerm.json"
    state: link
    force: true
  tags: 
    - iterm

- name: Link iTerm AutoLaunch Scripts 
  file: 
    src: "{{role_path}}/files/iTerm/change_default_profile.py"
    path: "{{iterm.autorun_dir}}/change_default_profile.py"
    state: link
    force: true
  tags: 
    - iterm

- name: iTerm Shell Integration
  shell: curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
  tags: 
    - iterm