- name: "Disable OSX Spotlight shortcut defaults"
  shell: > 
    /usr/libexec/PlistBuddy
    -c "delete :AppleSymbolicHotKeys:64"
    -c "add :AppleSymbolicHotKeys:64:enabled bool false"
    -c "add :AppleSymbolicHotKeys:64:value:type string standard"
    -c "add :AppleSymbolicHotKeys:64:value:parameters array"
    -c "add :AppleSymbolicHotKeys:64:value:parameters: integer 32"
    -c "add :AppleSymbolicHotKeys:64:value:parameters: integer 49"
    -c "add :AppleSymbolicHotKeys:64:value:parameters: integer 1048576"
    ~/Library/Preferences/com.apple.symbolichotkeys.plist
  ignore_errors: true
   
- name: Check if Raycast has completed onboarding
  community.general.osx_defaults:
    domain: com.raycast.macos
    key: onboardingCompleted
    state: list
  register: raycastOnboarded

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: raycastOnboarded

- name: Onboard Raycast
  block: 
    - name: Open Raycast
      ansible.builtin.shell: "open -Fna 'Raycast' && sleep 12"
      
    - name: Close load on startup notification
      ansible.builtin.shell: "cliclick m:1155,60 w:500 c:1155,60"

    - name: Start setup
      ansible.builtin.shell: "cliclick c:1350,850 w:1000"

    - name: Continue
      ansible.builtin.shell: "cliclick c:1350,850 w:1000"
    
    - name: Install extensions later
      ansible.builtin.shell: "cliclick c:1200,850 w:1000"

    - name: Setup Raycast Pro later
      ansible.builtin.shell: "cliclick c:1350,850 w:1000"

    - name: Continue for open at login
      ansible.builtin.shell: "cliclick c:1350,850 w:1000"

    - name: Grant calendar access
      ansible.builtin.shell: "cliclick c:1300,350 w:1000 c:750,400 w:1000"

    - name: Grant files and folders access
      ansible.builtin.shell: "cliclick c:1300,450 w:1000 c:800,385 w:500 c:800,385 w:500 c:800,385 w:500 c:800,385 w:500"

    - name: Grant accessibility
      ansible.builtin.shell: "cliclick c:1300,550 w:1000 c:800,375 w:500 c:1070,350"
  when: not raycastOnboarded.value
  tags: 
    - raycast
    - settings

