- name: "Disable OSX Spotlight shortcut defaults"
  shell: > 
    /usr/libexec/PlistBuddy
    -c "delete :AppleSymbolicHotKeys:64"
    -c "add :AppleSymbolicHotKeys:64:enabled bool false"
    -c "add :AppleSymbolicHotKeys:64:value:type string standard"
    -c "add :AppleSymbolicHotKeys:64:value:parameters array"
    -c "add :AppleSymbolicHotKeys:64:value:parameters: integer 32"
    -c "add :AppleSymbolicHotKeys:64:value:parameters: integer 49"
    -c "add :AppleSymbolicHotKeys:64:value:parameters: integer 1048576"
    ~/Library/Preferences/com.apple.symbolichotkeys.plist
  ignore_errors: true
   