- hosts: localhost
  connection: local
  pre_tasks: 
    - name: 1Password login check
      debug:
        msg: 
          - "{{ lookup('community.general.onepassword', 'HAL 9000') }}"
      tags: always
      # no_log: true
      
  roles:
      - { role: base, tags: ['base']}
      - { role: ssh, tags: ['ssh']}
      - { role: osx, tags: ['osx']}
      - { role: projects, tags: [projects]}
