- hosts: localhost
  pre_tasks:
    - name: Retrieve become password
      ansible.builtin.set_fact: 
        ansible_become_password: "{{ lookup('community.general.onepassword', 'Personal MacBook', field='password') }}"
      tags: ['always']
  roles:
      - { role: base, tags: ['base']}
      - { role: ssh, tags: ['ssh']}
      - { role: osx, tags: ['osx']}
      - { role: projects, tags: [projects]}
