- hosts: localhost
  connection: local
  roles:
      - { role: base, tags: ['base']}
      - { role: ssh, tags: ['ssh']}
      - { role: osx, tags: ['osx']}
      - { role: projects, tags: [projects]}
