ssh_dir: '{{ ansible_env.HOME }}/.ssh'
ssh_config: "{{ lookup('lastpass', 'SSH:config', field='notes') }}"
ssh_keys: 
  - keybase
  - locopia_rsa
  - personal_rsa
  - jenkins_rsa
  - sellercrowd_rsa
  - cohoot_rsa
  - am_key
  