sdks:
  - {name: groovy, version: 4.0.15} 
  - {name: gradle, version: 8.4}
  - {name: kotlin, version: 1.5.31}
  - {name: micronaut, version: 4.1.5}
  - {name: visualvm, version: 2.1.7}
  - {name: java, version: 17.0.9-tem}

etchosts: 
  - db
  - postgres
  - redis
  - teamtempo.local
  - api.teamtempo.local

project_owners_by_profile:
  base:
    - jamesdh
  personal:
    - jamesdh
    - moltenbits
  proximal:
    - jamesdh
    - proximal-health
  dev:
    - jamesdh
    - moltenbits
active_project_owners: "{{ project_owners_by_profile[machine_profile] | default(project_owners_by_profile.base) }}"

github: "{{vaulted_github}}"
envfiles:
  - { src: ph.env, dest: "{{projects_dir}}/proximal-health", owner: proximal-health }
makefiles: "{{vaulted_makefiles}}"
hooks: "{{vaulted_hooks}}"
growlrrr_repo_apps: "{{ vaulted_growlrrr_repo_apps }}"
growlrrr_apps:
  - appId: Homebrew
    icon: "{{ playbook_dir }}/roles/projects/files/homebrew.png"
