#!/bin/zsh

ZSH_THEME=""

zstyle :prompt:pure:path color cyan
zstyle :prompt:pure:virtualenv color cyan
zstyle :omz:plugins:nvm lazy yes
zstyle :omz:plugins:nvm autoload yes
zstyle :omz:plugins:nvm silent-autoload yes # optionally remove the output generated by NVM when autoloading
zstyle :omz:plugins:iterm2 shell-integration yes # see https://github.com/sindresorhus/pure/issues/680
plugins=(
    brew    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/brew
    direnv  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/direnv
    gcloud  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gcloud
    gradle  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gradle
    iterm2  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/iterm2
    nvm     # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/nvm
    pyenv   # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pyenv
    sdk     # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/sdk
)

fpath+=("$HOMEBREW_PREFIX/share/zsh/site-functions")

# Initialize SDKMAN
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

DISABLE_MAGIC_FUNCTIONS=true

source $ZSH/oh-my-zsh.sh

# Load the shell dotfiles, and then some:
# * ~/.extra can be used for other settings you don’t want to commit.
# Sourced AFTER oh-my-zsh so our aliases/functions win over the framework's,
# and so compdef (from omz's compinit) is available when .aliases runs.
for file in ~/.{aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Theme
autoload -U promptinit; promptinit
prompt pure

# Initialize Atuin (shell history)
eval "$(atuin init zsh)"
