#!/bin/zsh

export ZSH="$HOME/.oh-my-zsh"

# zstyle ':omz:plugins:nvm' lazy no
# zstyle ':omz:plugins:nvm' autoload yes
# zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading
zstyle :omz:plugins:iterm2 shell-integration yes
plugins=(
    brew    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/brew
    direnv  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/direnv
    gcloud  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/gcloud
    iterm2  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/iterm2
    nvm     # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/nvm
    pyenv   # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pyenv
    sdk     # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/sdk
)

FPATH="$HOMEBREW_PREFIX/share/zsh/site-functions:${FPATH}"

# Prompt colors
autoload -U promptinit
promptinit
prompt pure

# Load the shell dotfiles, and then some:
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Initialize SDKMAN
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

source $ZSH/oh-my-zsh.sh
