
- name: Setup SSH dir
  file: 
    path: '{{ ssh_dir }}'
    mode: 0700
    state: directory

- name: Setup certs dir
  file: 
    path: '{{ cert_dir }}'
    mode: 0700
    state: directory
    
# See https://github.com/ansible-collections/community.general/issues/7435
# - name: SSH config
#   community.general.ssh_config:
#     user: jamesdh
#     forward_agent: true
#     host: "*"
#     identity_agent: "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
#     state: present

# See https://github.com/ansible-collections/community.general/issues/7246
# - name: Retrieve Private Keys
#   copy: 
#     content: "{{ lookup('community.general.onepassword', item, type='document') }}"
#     dest: '{{ ssh_dir }}/{{ item }}' 
#     mode: 0600
#   loop: '{{ ssh_keys }}'
#   loop_control:
#     label: '{{ item }}'
  
# - name: Retrieve Public Keys
#   copy: 
#     content: "{{ lookup('community.general.onepassword', item + '.pub', type='document') }}"
#     dest: '{{ ssh_dir }}/{{ item }}.pub' 
#     mode: 0644
#   loop: '{{ ssh_keys }}'
#   loop_control:
#     label: '{{ item }}'

# - name: Retrieve other certificates
#   copy: 
#     src: "{{ lookup('community.general.onepassword', item, type='document' }}"
#     dest: '{{ cert_dir }}/{{ item }}' 
#     mode: 0644
#   loop: '{{ certs }}'
#   loop_control:
#     label: '{{ item }}'

- name: remove tmpfiles
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: 
    - "{{lookup('env','TMPDIR')}}ansible-onepassword-*"
