
- name: Setup SSH dir
  file: 
    path: '{{ ssh_dir }}'
    mode: 0700
    state: directory

- name: Setup certs dir
  file: 
    path: '{{ cert_dir }}'
    mode: 0700
    state: directory

- name: Use 1Password for all SSH keys
  copy: 
    src: "{{role_path}}/files/config"
    dest: '{{ ssh_dir }}/config'
    mode: 0600
    
# - name: Retrieve other certificates
#   copy: 
#     src: "{{ lookup('community.general.onepassword', item, type='document' }}"
#     dest: '{{ cert_dir }}/{{ item }}' 
#     mode: 0644
#   loop: '{{ certs }}'
#   loop_control:
#     label: '{{ item }}'

- name: remove tmpfiles
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: 
    - "{{lookup('env','TMPDIR')}}ansible-onepassword-*"
