---
- name: Configure Contexts
  block: 
    
    - name: Create tempory file to hold Contexts license
      tempfile:
        state:  file
        suffix: .contexts-license
      register: tempfile

    - name: Download license
      get_url:
        url: '{{ contexts.license_url }}'
        dest: "{{ tempfile.path }}"
        mode: 0600
        force: true

    - name: Open license file to register licence with Contexts
      shell: "open {{ tempfile.path }}"

    - name: Remove license file
      file:
        path: "{{ tempfile.path }}"
        state: absent
  
  tags: 
    - contexts
    - settings