instance_eval(File.read("roles/osx/files/Brewfile.bootstrap"))
instance_eval(File.read("roles/osx/files/Brewfile.priority"))
instance_eval(File.read("roles/osx/files/Brewfile.nonpriority"))
instance_eval(File.read("roles/osx/files/Brewfile.fonts"))
