- name: Git config username
  git_config: 
    name: user.name
    scope: global
    value: James Hardwick

- name: Git config email
  git_config: 
    scope: global
    name: user.email
    value: jamesdh@gmail.com

- name: Git config signing key
  git_config:
    scope: global
    name: user.signingkey
    value: "{{keys.public.github}}"

- name: Git gpg format
  git_config:
    scope: global
    name: gpg.format
    value: ssh

- name: Git config gpg program
  git_config:
    scope: global
    name: gpg.ssh.program
    value: "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

- name: Git config commit signing
  git_config:
    scope: global
    name: commit.gpgsign
    value: "true"

- name: Git config merge tool
  git_config: 
    scope: global
    name: mergetool.p4merge.cmd
    value: "{{apps_dir}}/p4merge.app/Contents/MacOS/p4merge $BASE $LOCAL $REMOTE $MERGED"
  
- name: Git config merge tool
  git_config: 
    scope: global
    name: mergetool.p4merge.keeptemporaries
    value: "false"
  
- name: Git config merge tool
  git_config: 
    scope: global
    name: mergetool.p4merge.trustexitcode
    value: "false"
  
- name: Git config merge tool
  git_config: 
    scope: global
    name: mergetool.p4merge.keepbackup
    value: "false"

- name: Git config merge tool
  git_config: 
    scope: global
    name: merge.tool
    value: p4merge
  
- name: Git config difftool
  git_config: 
    scope: global
    name: difftool.p4merge.cmd
    value: "{{apps_dir}}/p4merge.app/Contents/MacOS/p4merge $BASE $LOCAL"
  
- name: Git config diff tool
  git_config: 
    scope: global
    name: diff.tool
    value: p4merge

- name: Check if Git LFS is installed
  git_config:
    scope: global
    name: filter.lfs.process
  register: lfs_config

- name: Install Git LFS if not already installed
  shell: git lfs install
  when: '"git-lfs" not in lfs_config.config_value'

