- name: Configure repository-backed Growlrrr apps
  include_tasks: per_app/grrr_app.yml
  loop: "{{ growlrrr_repo_apps }}"
  loop_control:
    label: "{{ item.appId }}"
  tags:
    - grrr

- name: Configure standalone Growlrrr apps
  include_tasks: per_app/grrr_app.yml
  loop: "{{ growlrrr_apps }}"
  loop_control:
    label: "{{ item.appId }}"
  tags:
    - grrr

- name: Authorize repository-backed Growlrrr app notifications
  include_tasks: per_app/grrr_app_permissions.yml
  loop: "{{ growlrrr_repo_apps }}"
  loop_control:
    label: "{{ item.appId }}"
  tags:
    - permissions

- name: Authorize standalone Growlrrr app notifications
  include_tasks: per_app/grrr_app_permissions.yml
  loop: "{{ growlrrr_apps }}"
  loop_control:
    label: "{{ item.appId }}"
  tags:
    - permissions
