---

- name: Install Visual Studio Code extensions
  shell: "code --install-extension {{ item }}"
  loop: "{{ vscode.extensions }}"

- name: Link Visual Studio Code settings files
  file: 
    src: "{{role_path}}/files/{{ item }}"
    path: "{{ vscode.userpath }}/{{ item }}"
    state: link
    force: true
  loop: 
    - settings.json
    - keybindings.json