---
- name: Configure git 
  import_tasks: git.yml
  tags: 
    - git
    - gitconfig
    - priority

- name: Configure repos
  import_tasks: repos.yml
  tags:
    - git
    - repos
    - priority
    
- name: Configure dev environment
  import_tasks: env.yml
  tags: 
    - devenv
    
- name: Configure SDK's
  import_tasks: sdk.yml
  tags:
    - sdk
