---
- name: Configure git 
  import_tasks: git.yml
  tags: 
    - git

- name: Configure repos
  import_tasks: repos.yml
  tags:
    - git
    - repos
    
- name: Configure SDK's
  import_tasks: sdk.yml
  tags:
    - sdk

- name: Configure IDE's
  import_tasks: ide.yml
  tags:
    - ide
    