---
- name: Configure git 
  import_tasks: git.yml
  tags: 
    - gitconfig

- name: Configure repos
  import_tasks: repos.yml
  tags:
    - git
    - repos
    
- name: Configure dev environment
  import_tasks: env.yml
  tags: 
    - devenv
    
- name: Configure SDK's
  import_tasks: sdk.yml
  tags:
    - sdk

- name: Configure makefiles
  import_tasks: makefiles.yml
  tags:
    - makefiles
