---

- name: Get list of projects that already exist
  # shell: ls -d -1 "$PWD"*/*/
  shell: find "$PWD" -type d -maxdepth 2 -mindepth 2 -print
  args:
    chdir: "{{projects_dir}}"
  register: projects_ls
  tags:
    - priority
    
# I mostly just do this because "dotfiles" is initially checked out using https
# This takes care of fixing it so I can easily modify and push changes 
- name: Verify repo origin url for projects already in place
  git_config:
    scope: local
    repo: "{{projects_dir}}/{{item.0.org}}/{{item.1.name}}"
    name: remote.origin.url
    value: "git@github.com:{{item.0.org}}/{{item.1.name}}.git"
  with_subelements:
    - "{{github}}"
    - repos
  when: "[item.0.org,item.1.name] | join('/') in projects_ls.stdout"
  tags:
    - priority

- name: Setup git repositories 
  git:
    repo: "git@github.com:{{item.0.org}}/{{item.1.name}}.git"
    dest: "{{projects_dir}}/{{item.0.org}}/{{item.1.name}}"
    accept_hostkey: true
  with_subelements:
    - "{{github}}"
    - repos
  when: "not [item.0.org,item.1.name] | join('/') in projects_ls.stdout"

- name: Setup repo pre-commit hooks
  file: 
    src: "{{role_path}}/files/{{item.file}}"
    path: "{{item.path}}/.git/hooks/pre-commit"
    state: link
    force: true
  loop: "{{hooks}}"
  tags: 
    - hooks

- name: Setup repo env files
  file:
    src: "{{role_path}}/files/{{item.src}}"
    path: "{{item.dest}}/.env"
    state: link
    force: true
  loop: "{{envfiles}}"
  tags:
    - envfiles

- name: Setup default .envrc files
  copy:
    src: "{{role_path}}/files/.envrc"
    dest: "{{item.dest}}/.envrc"
    force: false
  loop: "{{envfiles}}"
  tags:
    - envfiles

- name: Allow direnv on env files
  shell: direnv allow
  args:
    chdir: "{{item.dest}}"
  loop: "{{envfiles}}"
  changed_when: false
  tags:
    - envfiles

- name: Link Makefiles to relevant Projects dir
  file: 
    src: "{{role_path}}/files/{{item.file}}"
    path: "{{item.path}}/Makefile"
    state: link
    force: true
  loop: "{{makefiles}}"
  tags: 
    - makefiles