---

- name: Get list of projects that already exist
  # shell: ls -d -1 "$PWD"*/*/
  shell: find "$PWD" -type d -maxdepth 2 -mindepth 2 -print
  args:
    chdir: "{{projects_dir}}"
  register: projects_ls

# I mostly just do this because "dotfiles" is initially checked out using https
# This takes care of fixing it so I can easily modify and push changes 
- name: Verify repo origin url for projects already in place
  git_config:
    scope: local
    repo: "{{projects_dir}}/{{item.0.org}}/{{item.1}}"
    name: remote.origin.url
    value: "git@github.com:{{item.0.org}}/{{item.1}}.git"
  with_subelements:
    - "{{github}}"
    - repos
  when: "[item.0.org,item.1] | join('/') in projects_ls.stdout"

- name: Setup git repositories 
  git:
    repo: "git@github.com:{{item.0.org}}/{{item.1}}.git"
    dest: "{{projects_dir}}/{{item.0.org}}/{{item.1}}"
    accept_hostkey: true
  with_subelements:
    - "{{github}}"
    - repos
  when: "not [item.0.org,item.1] | join('/') in projects_ls.stdout"