- name: Create Projects dir
  file: 
    path: "{{ projects_dir }}"
    state: directory
    mode: 0700
  tags: 
    - dirs

- name: Link dotfiles to home dir
  file: 
    src: "{{role_path}}/files/dotfiles/{{ item }}"
    path: "{{home_dir}}/{{ item }}"
    state: link
    force: true
  loop: 
    - .aliases
    - .functions
    - .vimrc
    - .zshenv
    - .zshrc
  tags: 
    - dotfiles
    - preprompt

- name: Check if oh-my-zsh is already installed
  stat: 
    path: "{{home_dir}}/.oh-my-zsh"
  register: omz


- name: Install oh-my-sh
  block: 
    - name: Download install script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{home_dir}}/install_ohmyzsh.sh"

    - name: Run Oh My Zsh script
      command: "sh {{home_dir}}/install_ohmyzsh.sh --keep-zshrc"

    - name: Remove installer script
      file: 
        path: "{{home_dir}}/install_ohmyzsh.sh"
        state: absent

  when: not omz.stat.exists
