- name: Create Projects dir
  file: 
    path: "{{ projects_dir }}"
    state: directory
    mode: 0700
  tags: 
    - dirs

- name: Link dotfiles to home dir
  file: 
    src: "{{role_path}}/files/dotfiles/{{ item }}"
    path: "{{home_dir}}/{{ item }}"
    state: link
    force: true
  loop: 
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .curlrc
    - .exports
    - .functions
    - .path
    - .vimrc
  tags: 
    - dotfiles
    - preprompt

- name: Link fonts to ~/Library/Fonts
  copy: 
    src: "{{role_path}}/files/fonts/{{item.name}}/{{item.name}}-{{item.type}}.ttf"
    dest: "{{home_dir}}/Library/Fonts/{{item.name}}-{{item.type}}.ttf"
  loop: 
    - {name: Inconsolata, type: Regular}
  tags: 
    - fonts