- name: Install dev Homebrew apps
  shell: brew bundle --file={{ role_path }}/files/Brewfile
  register: brew_diff
  changed_when: '"Installing" in brew_diff.stdout'

- name: Install dev Homebrew apps - Changed output
  debug:
    var: brew_diff.stdout
  when:
    - brew_diff.changed
    - not ansible_check_mode
  changed_when: brew_diff.changed

- import_tasks: github_runner.yml
  tags:
    - runner
