- name: Install Homebrew Apps
  shell: export HOMEBREW_CASK_OPTS='--no-quarantine'; brew bundle --file=roles/osx/files/Brewfile.post
  register: brew_diff
  changed_when: '"Installing" in brew_diff.stdout'

- name: Install Homebrew Apps - Changed output
  debug:
    var: brew_diff.stdout
  when: 
    - brew_diff.changed
    - not ansible_check_mode
  changed_when: brew_diff.changed