# Do sudo using Touch ID
- name: Set content of sudo file as fact
  set_fact:
    sudo_conf: "{{ lookup('file', '/etc/pam.d/sudo') }}"
  ignore_errors: yes
  tags:
    - touchid

# See...
# https://browniebroke.com/blog/enabling-sudo-via-touchid-using-ansible/
# https://apple.stackexchange.com/a/355880
# https://github.com/fabianishere/pam_reattach
- name: Set sudo via Touch ID if not setup
  become: yes
  command: sed -i '' 's/auth       sufficient     pam_smartcard.so/auth       sufficient     pam_smartcard.so\nauth       optional       \/opt\/homebrew\/lib\/pam\/pam_reattach.so\nauth       sufficient     pam_tid.so/g' /etc/pam.d/sudo
  when: "'auth       sufficient     pam_tid.so' not in sudo_conf"
  tags:
    - touchid