
- name: "OSX {{ domain }} defaults"
  osx_defaults:
    domain: "{{ domain }}"
    key: "{{ item.key }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
    host: "{{ item.value.host | default('')}}"
  loop: "{{ keys | dict2items }}"
  loop_control:
    label: "{{item.key}}:{{item.value.type}}:{{item.value.value}} {{ item.value.host | default('')}}"
  tags:
    - defaults 