- name: Setup auth/security customizations
  import_tasks: auth.yml
  tags: 
    - auth

- name: Install applications necessary for immediate permissions approvals
  import_tasks: apps.pre.yml
  tags: 
    - preinstall
    - apps

- name: Install core applications
  import_tasks: apps.yml
  tags:
    - apps

- name: Install fonts
  import_tasks: fonts.yml
  tags: 
    - fonts

- name: Install Nativefier applicaitons
  include_tasks: nativefier.yml
  tags:
    - apps
    - nativefier
  loop: "{{nativefier}}"
  
- name: Configure OS settings
  import_tasks: settings.yml
  tags: 
    - settings

- name: Configure Learned Spellings Dictionary
  import_tasks: spelling.yml
  tags:
    - dictionary

- name: Install remaining applications
  import_tasks: apps.post.yml
  tags:
    - apps
    - postinstall