- name: Setup auth/security customizations
  import_tasks: auth.yml
  tags: 
    - auth
    - priority

- name: Install applications necessary for immediate permissions approvals
  import_tasks: apps.pre.yml
  tags: 
    - preinstall
    - apps
    - priority

- name: Install core applications
  import_tasks: apps.yml
  tags:
    - apps

- name: Install fonts
  import_tasks: fonts.yml
  tags: 
    - fonts

- name: Configure OS settings
  import_tasks: settings.yml
  tags: 
    - settings
    - priority

- name: Configure Learned Spellings Dictionary
  import_tasks: spelling.yml
  tags:
    - dictionary