- name: Install applications necessary for immediate permissions approvals
  import_tasks: apps.pre.yml
  tags: 
    - preinstall

- name: Install core applications
  import_tasks: apps.yml
  tags:
    - apps

- name: Configure OS settings
  import_tasks: settings.yml
  tags: 
    - settings

- name: Configure Learned Spellings Dictionary
  import_tasks: spelling.yml
  tags:
    - dictionary