
- block: 

  - name: Check if already installed
    stat: 
      path: "{{apps_dir}}/{{item.name}}.app"
    register: st

  - name: Install {{item.name}} arm64 app
    block:   

      - name: Build {{item.name}}
        shell: "nativefier -n '{{item.name}}' --internal-urls '.*' '{{item.url}}'"
  
      - name: Move built {{item.name}} app to {{apps_dir}}
        shell: "mv {{item.name | regex_replace('\\s', '\\ ')}}-darwin-arm64/{{item.name | regex_replace('\\s', '\\ ')}}.app {{apps_dir}}/"
        when: ansible_architecture == "arm64"
      
      - name: Cleanup remaining artifacts
        file: 
          path: "{{item.name}}-darwin-arm64"
          state: absent

    when: 
     - ansible_architecture == "arm64"
    #  - not st.stat.exists
  
  tags: 
    - apps
    - nativefier
