# TODO: This assumes we are only using a MacBook Pro 13" ProMotion screen
# - name: "Set preferred resolution" 
#   shell: "displayplacer 'res:1800x1169 hz:120 color_depth:8 enabled:true scaling:on origin:(0,0) degree:0'"
#   changed_when: false
  
- name: "Set preferred power settings when on battery"
  shell: "pmset -b displaysleep 5 sleep 5"
  changed_when: false
  become: true

- name: "Set preferred power settings when connected"
  shell: "pmset -c displaysleep 10 sleep 0"
  changed_when: false
  become: true

- include_tasks: defaults.yml
  vars: 
    domain: "{{ domain_item.key }}"
    keys: "{{ domain_item.value }}"
  loop: >
    {{ defaults.ui 
    | combine(defaults.devices, recursive=true) 
    | combine(defaults.finder, recursive=true) 
    | combine(defaults.dock, recursive=true) 
    | combine(defaults.safari, recursive=true) 
    | combine(defaults.timemachine, recursive=true)
    | combine(defaults.sysapps, recursive=true)
    | combine(defaults.userapps, recursive=true)
    | combine(defaults.touchbar, recursive=true)
    | dict2items }}
  loop_control:
    label: ""
    loop_var: domain_item
  tags: 
    - defaults

- import_tasks: per_app/finder.yml
  tags: 
    - finder

- name: "Restart affected services"
  shell: "killall cfprefsd Dock Finder Safari SystemUIServer TouchBarServer Divvy"
  become: true
  tags: 
    - restart

- import_tasks: per_app/divvy.yml
- import_tasks: per_app/contexts.yml
# - import_tasks: per_app/viscosity.yml
# - import_tasks: per_app/ngrok.yml
- import_tasks: per_app/iterm.yml
  tags: 
    - iterm

- name: "Link iCloud Drive to home dir for easier CLI access"
  file: 
    src: "~/Library/Mobile\ Documents/com~apple~CloudDocs/"
    dest: "~/iCloud"
    state: link
  tags: 
    - icloud
