
- include_tasks: defaults.yml
  vars: 
    domain: "{{ domain_item.key }}"
    keys: "{{ domain_item.value }}"
  loop: >
    {{ defaults.ui 
    | combine(defaults.devices, recursive=true) 
    | combine(defaults.finder, recursive=true) 
    | combine(defaults.dock, recursive=true) 
    | combine(defaults.safari, recursive=true) 
    | combine(defaults.timemachine, recursive=true)
    | combine(defaults.sysapps, recursive=true)
    | combine(defaults.userapps, recursive=true)
    | dict2items }}
  loop_control:
    label: ""
    loop_var: domain_item
  tags: 
    - defaults

- import_tasks: per_app/finder.yml
  tags: 
    - finder

- name: "Restart Dock"
  shell: "killall Dock"
  tags: 
    - dock

- import_tasks: per_app/divvy.yml
- import_tasks: per_app/contexts.yml
- import_tasks: per_app/viscosity.yml