
- name: "Set preferred resolution" 
  shell: "/Applications/RDM.app/Contents/MacOS/SetResX -w 1680 -h 1050 -s 2.0"
  changed_when: false
  
- name: "Set preferred power settings when on battery"
  shell: "pmset -b displaysleep 5 sleep 5"
  changed_when: false
  become: true

- name: "Set preferred power settings when connected"
  shell: "pmset -c displaysleep 10 sleep 0"
  changed_when: false
  become: true

- include_tasks: defaults.yml
  vars: 
    domain: "{{ domain_item.key }}"
    keys: "{{ domain_item.value }}"
  loop: >
    {{ defaults.ui 
    | combine(defaults.devices, recursive=true) 
    | combine(defaults.finder, recursive=true) 
    | combine(defaults.dock, recursive=true) 
    | combine(defaults.safari, recursive=true) 
    | combine(defaults.timemachine, recursive=true)
    | combine(defaults.sysapps, recursive=true)
    | combine(defaults.userapps, recursive=true)
    | combine(defaults.touchbar, recursive=true)
    | dict2items }}
  loop_control:
    label: ""
    loop_var: domain_item
  tags: 
    - defaults

- import_tasks: per_app/finder.yml
  tags: 
    - finder

- import_tasks: per_app/bash.yml
  tags: 
    - bash

- name: "Restart affected services"
  shell: "killall cfprefsd Dock Finder Safari SystemUIServer TouchBarServer"
  become: true
  tags: 
    - restart

- import_tasks: per_app/divvy.yml
- import_tasks: per_app/contexts.yml
- import_tasks: per_app/viscosity.yml