
- include_tasks: defaults.yml
  vars: 
    domain: "{{ domain_item.key }}"
    keys: "{{ domain_item.value }}"
  loop: >
    {{ defaults.ui 
    | combine(defaults.devices, recursive=true) 
    | combine(defaults.finder, recursive=true) 
    | combine(defaults.dock, recursive=true) 
    | combine(defaults.safari, recursive=true) 
    | combine(defaults.timemachine, recursive=true)
    | combine(defaults.sysapps, recursive=true)
    | combine(defaults.userapps, recursive=true)
    | dict2items }}
  loop_control:
    label: ""
    loop_var: domain_item
  tags: 
    - defaults

- name: Remove undesired Finder sidebar items
  shell: "mysides remove '{{ item.key }}'"
  loop: "{{ finder_dels | dict2items }}"
  ignore_errors: true
  tags: 
    - finder

- name: Add desired Finder sidebar items
  shell: "mysides add '{{ item.name }}' {{ item.path }}"
  loop: "{{ finder_adds }}"
  ignore_errors: true
  tags: 
    - finder

- name: Show hidden folders
  command: "chflags nohidden {{ item }}"
  become: true
  loop: 
    - "{{ home_dir }}/Library"
    - /Volumes
  tags:
    - finder

- name: "Restart Dock"
  shell: "killall Dock"
  tags: 
    - dock

- import_tasks: settings/divvy.yml
- import_tasks: settings/contexts.yml
- include_tasks: settings/viscosity.yml
  loop: "{{viscosity}}"
  tags: 
    - vpn